description = "Turn glance AST into a Ballerina source code"
gleam = ">= 0.32.0"
name = "glance_printer_bal"
version = "0.1.0"

licences = ["Apache-2.0"]
repository = {type = "codeberg", user = "salif", repo = "glance_printer_bal"}

[dependencies]
glam = "~> 1.0"
glance = "~> 0.8.1"
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
simplifile = "~> 1.6"
testbldr = "~> 1.1"
